# Generated by Django 5.2.4 on 2025-08-07 01:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportedMalicious',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='IP Address')),
                ('abuse_confidence_score', models.IntegerField()),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('isp', models.CharField(blank=True, max_length=100, null=True)),
                ('last_reported_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP Address')),
                ('label', models.CharField(help_text='Signifies as source or destination ip', max_length=3, verbose_name='SRC/DST IP Address')),
                ('ports', models.CharField(help_text='SPT/DPT', max_length=30)),
                ('timestamp', models.CharField(help_text='Log timestamp', max_length=30)),
                ('reported_malicious', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='core.reportedmalicious')),
            ],
        ),
    ]
