# Generated by Django 5.2.4 on 2025-08-08 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyrequests',
            options={'verbose_name': 'Daily Request', 'verbose_name_plural': 'Daily Requests'},
        ),
        migrations.AlterModelOptions(
            name='reportedmalicious',
            options={'verbose_name': 'Reported Malicious IP', 'verbose_name_plural': 'Reported Malicious IPs'},
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Request Log', 'verbose_name_plural': 'Request Logs'},
        ),
        migrations.AlterField(
            model_name='requests',
            name='ports',
            field=models.CharField(blank=True, help_text='SPT/DPT', max_length=30, null=True),
        ),
    ]
