# Generated by Django 5.2.4 on 2025-08-09 20:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_dailyrequests_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyrequests',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyrequests',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True),
        ),
    ]
